theme = "blist"
languageCode = "en-US"
baseurl = "https://blist.vercel.app"
title = "Food For Thought"

[params]
  description = "Eating healthy matters"
  name = "Food For Thought"
  
  # Enable the darkmode toggle in header
  darkModeToggle = true
  
  # Enable search in header
  enableSearch = true

  # Custom copyright - optional
  copyright = "Copyright © 2021 - Me"
  favicon = "favicon.svg"

  # Color for the intro details and social links block, not applicable for dark mode
  # Supported values: Any color from TailwindCSS default colors
  # Reference: https://tailwindcss.com/docs/customizing-colors
  ascentColor = "bg-green-100"

[params.homepage]
  title = "Food For Thought"
  description = "eating healthy matters."
  photo = "/nature.jpg"

[params.homepage.social]
  title = "Eat, but healthy :)"
  description = ""

[[menu.main]]
  name = "About"
  url = "/about"

[[menu.main]]
  name = "Forum"
  url = "/forum"

[build]
  writeStats = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true
